openapi: 3.0.0
info:
  title: Awesome Coffee Shop App
  version: 1.0.0
  description: A mobile app for placing orders for Awesome Coffee Shop

paths:
  /orders:
    get:
      summary: Get all orders
      parameters:
        - name: status
          in: query
          description: Shows all orders, starting with most urgent at the top
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Submit a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Order created and placed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{orderId}:
    get:
      summary: Get a order by orderID
      parameters:
        - name: orderId
          in: path
          description: Gets the order requested via specific ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete an order via ID
      parameters:
        - name: orderId
          in: path
          description: ID of the order requested to be deleted
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Order already fulfilled
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              quantity:
                type: integer
                format: int32
        status:
          type: string
          enum: [being-placed, in-progress, ready, fulfilled]
      required:
        - id
        - items
        - status

    NewOrder:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              quantity:
                type: integer
                format: int32
      required:
        - items

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
